package com.example.medical;

import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;

import androidx.appcompat.app.AppCompatActivity;

public class LeerPoliticasActivity extends AppCompatActivity {

    private TextView textViewPoliticas;
    private TextView tituloPoliticas;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.n03_1_politicas);

        textViewPoliticas = findViewById(R.id.textViewPoliticas);
        tituloPoliticas = findViewById(R.id.tituloPoliticas);

        Button buttonFlagArg = findViewById(R.id.buttonFlagArg);
        mostrarTextoEspaniol();

        ImageView backButton = findViewById(R.id.boton_cerrar);

        backButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                // Acción de volver hacia atrás
                onBackPressed();
            }
        });
        buttonFlagArg.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                mostrarTextoEspaniol();
            }
        });

        Button buttonFlagUsa = findViewById(R.id.buttonFlagUsa);
        buttonFlagUsa.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                mostrarTextoIngles();
            }
        });
    }

    private void mostrarTextoEspaniol() {
        String textoEspaniol =
                "POLÍTICA DE PRIVACIDAD – PROYECTO MediCAL\n\n" +
                        "Tenemos en alta estima su privacidad y su información personal y estamos al tanto que el éxito de nuestros servicios depende de la confianza que usted tiene en la forma que manejamos su información personal. Al confiar en nosotros su información, nos gustaría asegurarle sobre nuestro compromiso en mantener tal información en privado. Hemos tomado ciertas medidas considerables para proteger la confidencialidad, seguridad e integridad de esta información. Lo animamos a repasar la siguiente información cuidadosamente.\n\n" +
                        "La política de privacidad aplica a su uso de la aplicación de dispositivos móviles MediCAL (la “Aplicación”) y a la página web relacionada (Incluyendo sus versiones optimizadas para dispositivos móviles, considerándose colectivamente como el “Sitio”) propiedad del Proyecto MediCAL (“Nosotros”). La aplicación y el sitio son referidos en conjunto como el “Servicio”. “Usted” hace referencia a cualquier usuario del Servicio.\n\n" +
                        "La política establece nuestro compromiso y explica los derechos que usted tiene con respecto a su información personal. Es posible que esta política sea actualizada cada cierto tiempo. Cualquier cambio será efectivo inmediatamente luego de la publicación de la Política de Privacidad actualizada. Lo animamos a revisar periódicamente esta Política de Privacidad para estar al tanto de la información más reciente en nuestras prácticas de privacidad. Si usted no está de acuerdo con los términos de esta Política de Seguridad, por favor no utilice este Servicio.\n\n" +
                        "BASES PARA LA RECOLECCIÓN DE DATOS\n" +
                        "Al utilizar nuestro servicio, usted consiente la recolección, almacenamiento, uso, divulgación y otros usos de su información personal como se describe en esta Política de Privacidad.\n" +
                        "Procesar su Información Personal (es decir, cualquier información que potencialmente permita identificarlo de manera razonable; de aquí en adelante “Información Personal”) es necesaria para el cumplimiento de nuestras obligaciones contractuales hacia usted y para poder proveer nuestro Servicio, para proteger nuestros intereses legítimos, para garantizar el cumplimiento de obligaciones legales y financieras reglamentarias, o de otra forma, sujeto a su consentimiento.\n\n" +
                        "CÓMO RECIBIMOS INFORMACIÓN SOBRE USTED\n" +
                        "Mientras usted use algunas de las funcionalidades de nuestro Servicio sin crear un perfil o registrarse, ciertas herramientas del Servicio requieren el registro y disposición de su información, incluyendo Información Personal.\n\n" +
                        "● Si usted elige crear un perfil o registrarse con nosotros - se le solicitará proveer Información Personal la cual será asociada a su Información de Salud.\n" +
                        "● Siempre que usted envíe información a través de nuestro Servicio - incluyendo, pero no limitado a, teléfono o email con servicio al cliente, podremos recolectar Información de Salud e Información Personal que nos ha proporcionado, para poder proveer nuestro Servicio.\n" +
                        "● Terceros - Podemos recibir información sobre usted de parte de nuestros socios, tales como empresas farmacéuticas y proveedores médicos en el contexto de nuestras actividades de marketing, como se describe a continuación en esta política.\n\n" +
                        "Es su decisión voluntaria si usted nos proporciona cualquier tipo de Información Personal o Información de Salud, sin embargo si usted no provee esta información no será capaz de crear un perfil o registrarse con el Servicio y el uso del mismo será limitado.\n\n" +
                        "QUÉ TIPO DE INFORMACIÓN RECOLECTAMOS\n" +
                        "Información Personal\n" +
                        "Es posible que recolectemos la siguiente Información Personal sobre usted:\n\n" +
                        "Información de Contacto - Su nombre, género, fecha de nacimiento, dirección de correo electrónico y número de teléfono.\n" +
                        "Información de Contacto de Emergencia - Si usted opta por usar las funciones de Contacto de Emergencia de la Aplicación, también recibiremos la información del contacto (tal como su nombre, número de teléfono, domicilio y dirección de correo electrónico) del Contacto de Emergencia que ha elegido.\n" +
                        "Información Adicional - Mientras usted use nuestra Aplicación, sujeto a su permiso, podemos obtener acceso a su lista de contactos y a su calendario. Además, si usted elige hacer uso de la funcionalidad de fotos de medicamentos, será requerido que usted conceda el acceso a su cámara y a las fotos guardadas en su dispositivo.\n" +
                        "Si usted es un profesional sanitario - Le solicitaremos proveer información relacionada a sus cualificaciones profesionales además de su Información Personal.\n" +
                        "Información Voluntaria - Cuando se comunica con nosotros (por ejemplo cuando nos envía un email o utiliza el formulario “contáctenos”) nosotros recolectamos su dirección de correo electrónico, y la Información Personal que nos ha facilitado en la comunicación.\n" +
                        "Información Personal de Salud - Usted puede elegir utilizar ciertas funcionalidades del Servicio que le permitan ingresar más Información Personal respecto a su salud, tales como medicamentos que consume, fecha de sus recetas, recargas que ha hecho, la frecuencia con la que toma sus medicamentos, dosis y mediciones físicas. (colectivamente su “Información de Salud”)\n\n" +
                        "Información de carácter no personal\n" +
                        "Sitio web:\n" +
                        "Datos de uso del sitio web - Recolectamos información acerca de su uso del Sitio, incluyendo, entre otras cosas: tipo de dispositivo móvil o informático que utiliza, idioma de su sistema operativo, Navegador de internet que utiliza, geolocalización y uso del Sitio.\n" +
                        "Información de Salud - También podemos recolectar su Información de Salud no identificable si decide proveerla (en caso de usuarios no registrados).\n" +
                        "TECNOLOGÍAS DE SEGUIMIENTO - COOKIES\n" +
                        "Una cookie es un pequeño fragmento de texto enviado al navegador del visitante. El navegador provee este fragmento de texto al dispositivo de origen del visitante cuando este vuelve a acceder. Usamos cookies para ayudar a personalizar su experiencia MediCAL. Usted es libre de eliminar cualquier cookie existente en cualquier momento. Si usted elimina o deshabilita cookies de nuestro Sitio, algunas partes o funciones del Sitio pueden no funcionar correctamente para usted.\n" +
                        "Un cookie “persistente” será utilizado para ayudarlo a guardar sus configuraciones y personalizaciones. También, si ingresa al Sitio, esta cookie será utilizada para reconocerlo como un usuario válido y ahorrar el inicio de sesión cada vez que utilice el Sitio.\n" +
                        "La mayoría de los navegadores Web aceptan automáticamente las cookies y le permiten a usted modificar la configuración de seguridad para aprobar o rechazar cookies en cada caso, o simplemente rechazar todas las cookies. Usted puede configurar su navegador para eliminar cookies siguiendo las instrucciones de la sección de “ayuda” proporcionada por su navegador de Internet.\n" +
                        "- Safari\n" +
                        "- Opera\n" +
                        "- Firefox\n" +
                        "- Google chrome\n" +
                        "- Internet explorer"+

                        "CÓMO UTILIZAMOS LA INFORMACIÓN QUE RECOLECTAMOS\n" +
                        "● Provisión del servicio - utilizamos la Información Personal que nos proporciona para la provisión y mejora de nuestro Servicio hacia usted, para operar nuestro negocio y proveer información que usted nos solicite. Por ejemplo, los datos recolectados automáticamente en el Servicio serán utilizados para ayudar a diagnosticar problemas con nuestros servidores, para hacer nuestro Servicio más útil y personalizar su contenido para usted (por ejemplo, utilizaremos su Información de Salud para enviarle recordatorios de consumo de medicamentos).\n" +
                        "● Comunicación general - también utilizamos su Información Personal para enviarle mensajes de texto, correos electrónicos u otro tipo de comunicación respecto a información de cumplimiento general, mantenimiento de Servicio y otro tipo de Soporte técnico, actualizaciones, o cambios a esta Política de Privacidad o cualquier otro acuerdo relevante, y para responder a sus consultas.\n" +
                        "● Fines de marketing - sujeto a sus preferencias de marketing, usaremos su Información Personal (tal como su dirección de email o su número de teléfono) para comunicarnos con usted. También le enviaremos material promocional relacionado a nuestros servicios o los de nuestros socios (que creemos que podrían interesarle), incluyendo, entre otros, crear un perfil automático basado en su Información Personal, para fines de marketing.\n" +
                        "○ No participar en recibir material de marketing - Si usted no desea que usemos y compartamos su Información Personal con fines de marketing, usted puede decidir no participar contactándonos de acuerdo a esta Política de Privacidad, al hacer clic en el botón de “desuscribirse” incluido en cada comunicación de marketing que recibe de nosotros, o con respecto a tecnologías de seguimiento, al usar las preferencias de cookies que se muestran en nuestro Sitio. Por favor tenga en cuenta que si usted decide no participar, seguiremos utilizando y compartiendo su Información Personal con terceros con fines ajenos al marketing (por ejemplo, para cumplir con sus solicitudes, comunicarnos con usted y responder sus consultas, etc).\n" +
                        "● Análisis, encuestas e investigación - siempre estamos intentando mejorar nuestros servicios y pensar en nuevas y emocionantes funcionalidades para nuestros usuarios. Cada cierto tiempo, llevaremos a cabo encuestas o funcionalidades de prueba, y analizaremos la información que tenemos para desarrollar, evaluar y mejorar estas funcionalidades.\n" +
                        "● Proteger nuestros intereses - podemos utilizar su Información Personal cuando creamos que sea necesario para tomar precauciones contra responsabilidades, investigar y defendernos contra alegaciones o demandas de terceros, investigar y protegernos del fraude, proteger la seguridad e integridad de nuestro Servicio y proteger los derechos de propiedad de MediCAL, sus usuarios y/o socios.\n" +
                        "● Aplicación de políticas - podemos utilizar su Información Personal para aplicar nuestras políticas, incluida, entre otras, la presente Política de Privacidad, los Términos y Condiciones y/o cualquier Programa aplicable de términos y políticas.\n" +
                        "● Cumplimiento de los requisitos legales y reglamentarios - También podemos utilizar su Información Personal cuando lo requiera la ley, regulaciones o cualquier otra autoridad gubernamental, o para cumplir con una citación o proceso legal similar.\n" +
                        "CON QUIÉN COMPARTIMOS SU INFORMACIÓN PERSONAL\n" +
                        "● Proveedores de contenidos personalizados de terceros - Cada cierto tiempo, podemos solicitar si desea que compartamos su Información Personal con otra empresa que pueda enviarle información sobre sus productos o servicios. Si usted da su consentimiento a esta transferencia de su Información Personal hacia otra empresa, por favor tenga en cuenta que la información provista estará sujeta a las prácticas de privacidad de tal empresa y no estará bajo nuestro control.\n" +
                        "● Proveedores de Servicio - Podemos compartir su Información Personal, lo razonablemente necesario, con nuestros proveedores de servicio, incluyendo vendedores y proveedores que nos brindan servicios de desarrollo, tecnología, servicios, o contenido para la operación, desarrollo y mantenimiento de nuestro Servicio o datos y análisis del uso del Servicio, que están sujetos a una obligación de confidencialidad, siempre que sólo compartamos Datos Personales en la medida necesaria con dichos proveedores de servicios.\n" +
                        "● Autoridades policiales: podemos compartir sus datos personales con las autoridades policiales, juzgados y tribunales, incluidos asesores y consultores jurídicos, en caso de que necesitemos responder a solicitudes policiales u otras solicitudes legales o en virtud de un requisito impuesto por ley, orden, sentencia o decreto, o tribunales con el fin de proteger y defender nuestros derechos y propiedad o los de los usuarios del Servicio.\n" +
                        "● Fusión, adquisición o venta: podemos transferir su Información Personal en caso de fusión, adquisición o venta de la totalidad o parte de nuestros activos.\n" +

                        "Su Información Personal no se combinará con otra información y no se utilizará para otros fines, salvo los explicados en esta política de privacidad. Tenga en cuenta que no estamos sujetos a obligaciones de secreto médico.\n" +
                        "● Información Personal que puede compartir a través de nuestro Servicio\n" +
                        "  ○ Contacto de Emergencia-\n" +
                        "    ■ Si utiliza los Servicios en su propio nombre: Podrá enviar a familiares o amigos una invitación para ser su \"Contacto de Emergencia\" a través del Servicio, de forma que dicha persona reciba alertas sobre el cumplimiento de su régimen de medicación. Si usted lo decide, los Contactos de Emergencia que elija también podrán recibir permisos para editar su información en los Servicios. Al enviar dicha invitación y conceder dichos permisos, usted declara que tiene derecho a designar y proporcionar la información de dicha persona; que da su consentimiento para que divulguemos Información Personal sobre sus medicamentos y el cumplimiento de su régimen de medicación a dicha persona; y, según corresponda, que permite a su Cuidador realizar cambios en los Servicios, incluida su información personal, en su nombre. Compartir su Información Personal y proporcionar los permisos de edición de esta manera son exclusivamente bajo su responsabilidad.\n" +
                        "    ■ Si utiliza los Servicios en nombre de su hijo o de una persona incapacitada, se le considerará el \"Contacto de Emergencia\" de dicha persona, según proceda. En tal caso, usted declara y garantiza que tiene la autoridad legal para actuar en nombre de esa persona; que mantendrá la confidencialidad y sólo utilizará la Información Personal puesta a su disposición a través de los Servicios para el propósito para el que se puso a su disposición; que cualquier permiso e información personal que se le proporcione a través de los Servicios se utilizará con el debido cuidado y sólo para el propio bien y el mejor interés de esa persona.\n" +
                        "  ○ Profesionales médicos y Doctores - Usted puede utilizar el Servicio con el fin de compartir su Información Personal u otra información con su médico o proveedores de atención médica. Este intercambio puede realizarse invitando a su profesional sanitario a supervisar su Información Personal, aceptando una invitación de su profesional sanitario para descargar y utilizar el Servicio, o utilizando de otro modo la configuración del Servicio para compartir su información con su profesional sanitario; en estos casos, usted da su consentimiento para que enviemos Información Personal sobre sus medicamentos y su cumplimiento del régimen de medicación con sus profesionales sanitarios. Confirme con su proveedor sanitario que le ha enviado una invitación para utilizar el Servicio. El uso compartido de su información queda a su discreción y es de su exclusiva responsabilidad.\n" +
                        "Aunque nos esforzamos por mantener la confidencialidad y seguridad de su Información Personal, cuando usted comparte información sobre su salud o medicación con otras personas o proporciona comentarios sobre temas de salud, medicación u otros, incluso a través de las redes sociales, o cuando participa en un foro del Servicio, cualquier información que usted revele de esa forma es de su exclusiva responsabilidad. Debe tener cuidado al revelar cualquier información (incluida la información personal) de esta forma, ya que no sabe quién accederá a ella o la utilizará y con qué fines.\n" +
                        "USO DE DATOS AGREGADOS\n" +
                        "Podemos desidentificar y agregar Información Personal; los datos agregados no contendrán ninguna información que pueda ser utilizada para contactarlo o identificarlo. Podremos analizar y/o combinar toda la información que recibamos, incluida la Información de Salud y la información relativa a su uso del Servicio, con información de otros usuarios para crear datos agregados que podrán ser divulgados y utilizados por nosotros, nuestros socios y por terceros sin restricciones, en las condiciones comerciales que podamos determinar a nuestra entera discreción, para fines tales como: marketing de contenidos, fines de investigación, con el fin de entender patrones de comportamiento, con el fin de aumentar la adherencia a los regímenes de medicación, estrategias de marketing y para la celebración de contratos comerciales con el fin de proporcionar a nuestros usuarios el Servicio.\n" +
                        "DERECHOS DEL USUARIO\n" +
                        "Las leyes de protección de datos de determinadas jurisdicciones otorgan a las personas ciertos derechos legales con respecto a su Información Personal.\n" +
                        "Cumplimos la legislación aplicable y respetamos los derechos de privacidad de nuestros usuarios. Si desea ejercer alguno de sus derechos o hacernos una pregunta, póngase en contacto con nosotros utilizando los datos de contacto que se facilitan a continuación.\n" +
                        "No obstante, tenga en cuenta que estos derechos no son absolutos y pueden estar sujetos a nuestros propios intereses legítimos y requisitos normativos.\n" +
                        "RETENCIÓN\n" +
                        "Conservaremos su Información Personal durante el tiempo que sea necesario para prestar los Servicios. Conservaremos y utilizaremos su información según sea necesario para cumplir con nuestras obligaciones legales, resolver conflictos y hacer cumplir nuestras políticas. Los periodos de conservación se determinarán teniendo en cuenta el tipo de información que se recoge y la finalidad para la que se recoge, teniendo en cuenta los requisitos aplicables a la situación.\n" +
                        "LINKS HACIA OTRAS PÁGINAS WEB O APLICACIONES\n" +
                        "Nuestro Servicio puede enlazar o remitir a sitios web o servicios de terceros que no son de nuestra propiedad ni están bajo nuestro control. Cualquier Información Personal que usted proporcione se facilita directamente a dicho tercero y está sujeta a la política de privacidad del proveedor de dicho tercero. Esta política de privacidad no se aplica a esos otros sitios web o servicios, y no somos responsables de las prácticas de privacidad o del contenido de ningún sitio web o servicio no controlado por nosotros, ni somos responsables del uso o mal uso que esos terceros hagan de su información personal. Si tiene alguna duda, le instamos a que consulte las condiciones de esos otros sitios web o servicios para obtener más información sobre sus políticas aplicables.\n" +
                        "CÓMO PROTEGEMOS SU INFORMACIÓN\n" +
                        "Hemos implantado medidas de seguridad administrativas, técnicas y físicas para evitar el acceso, uso o divulgación no autorizados de sus datos personales. Su información se almacena en servidores seguros y no está a disposición del público. Limitamos el acceso a su información sólo a aquellos empleados o socios que necesitan conocerla para poder llevar a cabo el acuerdo entre nosotros.\n" +
                        "Aunque tratamos de proteger su información para garantizar su confidencialidad, ningún sistema de seguridad es infalible e impermeable, y no podemos garantizar absolutamente su seguridad. Debe ser consciente de que la transmisión de información a través de Internet siempre conlleva cierto riesgo. Aunque nos esforzamos por proteger su Información Personal, no podemos asegurar o garantizar la seguridad y privacidad de su Información Personal u otro contenido que usted transmita utilizando el Servicio, y usted lo hace bajo su propia responsabilidad.\n" +
                        "Debe ayudarnos a evitar el acceso no autorizado a su cuenta protegiendo adecuadamente su contraseña y limitando el acceso a su cuenta (por ejemplo, cerrando la sesión cuando haya terminado de acceder a su cuenta). Usted será el único responsable de mantener la confidencialidad de su contraseña y de todo uso de su contraseña y de su cuenta, incluido cualquier uso no autorizado.\n" +
                        "NIÑOS\n" +
                        "Nuestro Servicio está destinado a ser utilizado por personas mayores de edad (según determine la legislación aplicable en el lugar donde residan dichas personas: \"Mayoría de edad\"), a menos que se nos proporcione una aprobación y consentimiento válido de los padres o tutores, de conformidad con los requisitos de las leyes aplicables. Bajo ninguna circunstancia el Servicio debe ser utilizado por personas menores de la Mayoría de Edad. No recopilaremos conscientemente Datos Personales de ninguna persona menor de la Mayoría de Edad a menos que se describa en el presente documento, y a nuestra entera discreción. Si descubre que un menor ha estado utilizando el Servicio sin su consentimiento, o que alguien ha estado utilizando el Servicio para o en nombre de su hijo sin su consentimiento, póngase en contacto con nosotros utilizando la información que aparece más abajo en \"Cómo contactarnos\" y tomaremos las medidas razonables para eliminar la información del menor de nuestras bases de datos activas. MediCAL se reserva el derecho de comprobar su base de usuarios de vez en cuando y eliminar a los usuarios que MediCAL tenga motivos para creer que en realidad son menores de edad, incluyendo, sin limitación, la restricción de esas cuentas de usuario, o su eliminación, según MediCAL considere apropiado.\n" +
                        "CÓMO CONTACTARNOS\n" +
                        "Si tiene alguna pregunta, comentario, solicitud o duda en relación con esta Política de Privacidad o con las prácticas de privacidad de nuestro Servicio, póngase en contacto con nosotros a través de:\n" +
                        "MediCAL\n" +
                        "info@MediCAL.com\n" +
                        "ATTN: MediCAL;\n";
        textViewPoliticas.setText(textoEspaniol);
        tituloPoliticas.setText("POLÍTICA DE PRIVACIDAD - PROYECTO MediCAL");


    }

    private void mostrarTextoIngles() {
        String textoIngles =
                "PRIVACY POLICY – MediCAL PROJECT\n" +
                        "We have the highest regard for your privacy and personal information and realize that the success of our services depends on the trust that you have in the way we handle your personal information. By entrusting us with your information, we would like to assure you of our commitment to keep such information private. We have taken considerable steps to protect the confidentiality, security and integrity of this information. We encourage you to review the following information carefully.\n\n" +
                        "This Privacy Policy applies to your use of the MediCAL mobile device applications (including the MediCAL App and MediCAL Maestro Link; collectively the “Apps”) and the related website (including their mobile-optimized versions, collectively the “Site”) owned by MediCAL Project. (“we” or “us”). The Apps and the Site are referred to together as the “Service”. “You” refers to any user of the Service.\n\n" +
                        "This policy sets out our commitments and explains the rights that you have with respect to your personal information. We may update this Privacy Policy from time to time. Any changes will be effective immediately upon the posting of the revised Privacy Policy. We encourage you to periodically review this Privacy Policy for the latest information on our privacy practices. If you do not agree to the terms of this Privacy Policy, please do not use the Service.\n\n" +
                        "GROUNDS FOR DATA COLLECTION\n" +
                        "When you use our Service, you consent to the collection, storage, use, disclosure and other uses of your personal information as described in this Privacy Policy.\n\n" +
                        "Processing of your Personal Information (meaning, any information which may potentially allow your identification with reasonable means; hereinafter “Personal Information”) is necessary for the performance of our contractual obligations towards you and providing you with our Service, to protect our legitimate interests, to ensure compliance with legal and financial regulatory obligations, or otherwise, subject to your consent.\n\n" +
                        "HOW DO WE RECEIVE INFORMATION ABOUT YOU\n" +
                        "While you may use some of the functionality of the Service without creating a profile or registration, certain tools of the Service require registration and provision of your information, including Personal Information.\n" +
                        "● If you choose to create a profile or register with us – you will be asked to provide Personal Information which will be associated with your Health information.\n" +
                        "● Whenever you submit information via our Service – including, but not limited to, by telephone or email with customer service, we may collect Health Information and other Personal Information you provide us, in order to provide you with our Service.\n" +
                        "● Third parties – we may receive information about you from our partners, such as pharmaceutical companies and medical providers as needed in order to provide you with our Service, and from other third parties in the context of our marketing activities, as further described in this policy.\n\n" +
                        "It is your voluntary decision whether to provide us with any Personal Information or Health Information, however if you do not provide this information you may not be able to create a profile or register with the Service and your use of the Service may be limited.\n\n" +
                        "WHAT TYPES OF INFORMATION DO WE COLLECT\n" +
                        "Personal Information\n" +
                        "We may collect the following Personal Information about you:\n" +
                        "Contact Information – your name, gender, birth date, email address, home address and/or office address, phone number and optionally, zip code.\n" +
                        "Caregiver or Medfriend Information – If you opt to use the Caregiver or Medfriend features of the Apps, we will also receive the contact information (such as name, phone number, address and email) of the Caregiver or Medfriend that you chose to appoint and provide us with their information.\n" +
                        "Additional information – while you are using our Apps, subject to your permission, we may obtain access to your contact list and to your calendar. In addition, if you choose to make use of the medicine picture feature , you will be required to grant us access to your camera and to the photos saved on your device.\n" +
                        "If you are a healthcare provider – you may be asked to provide information regarding your professional qualifications as well as additional Personal Information.\n\n" +
                        "Voluntary information – when you communicate with us (for example when you send us an email or use a “contact us” form) we collect your email address, and the Personal Information you provided us with within such communication.\n" +
                        "Personal Health Information – you may choose to use certain features of the Service that will allow you to input other Personal Information with respect to your health, such as the medications you take, the date of your prescriptions, refills you have made, how often you take your medication, dosage and physical measurements (collectively your “Health Information”).\n\n" +
                        "Non-Personal Information\n" +
                        "Site:\n" +
                        "Site usage data – We collect information about your use of the Site, including but not limited to: type of computing or mobile device you use, language of your operating system, the Internet browser you are using, geo-location and use of the Site.\n\n" +
                        "Health Information – We may also collect your non-identifiable Health Information if you choose to provide it (in case of non-registered users)\n\n" +
                        "Apps:\n" +
                        "Installation ID – When you download and install our App onto a mobile device, we assign a random number to your App installation. We do not use this number to identify you personally unless you choose to become a registered user of the App. We use this random number in a manner similar to our use of cookies as described in this Privacy Policy. Because the random number is assigned to your installation of the App itself, it cannot be removed through the settings of your App or your device. If you do not want us to use the random number for the purposes for which we use cookies, please do not install our App.\n\n" +
                        "Technical information – The App automatically collects certain information about you when you use the App, this includes, but not limited to: details of the Wi-Fi you use and accelerometer used on your device, type of computing or mobile device you use, advertiser ID, your device’s operating system, the language of your operating system and the Internet browser you are using. The App may also access a list of installed apps on your device. This is done only to ensure proper quality of service, as some apps might interfere with the App functionality.\n"+
                        "TRACKING TECHNOLOGIES – COOKIES\n" +
                        "A cookie is a small piece of text that is sent to a visitor’s browser. The browser provides this piece of text to the device of the originating visitor when this visitor returns. We use cookies to help personalize your MediCAL experience. You are free to delete any existing cookies at any time. If you delete or disable cookies from our Site, some parts or functions of the Site may not work properly for you.\n\n" +
                        "A “persistent” cookie may be used to help save your settings and customizations. Also, if you log in to the Site, such a cookie will be used to recognize you as a valid user so you will not need to log in each time you use the Site.\n\n" +
                        "Most Web browsers automatically accept cookies however allow you to modify security settings so you can approve or reject cookies on a case-by-case basis or reject all cookies. You can configure your web browser to remove cookies by following the directions provided in your Internet browser’s “help” section.\n" +
                        "- Safari\n" +
                        "- Opera\n" +
                        "- Firefox\n" +
                        "- Google Chrome\n" +
                        "- Internet Explorer\n"+
                        "HOW DO WE USE THE INFORMATION WE COLLECT\n" +
                        "● Provision of service – we use the Personal Information you provide us for the provision and improvement of our Service to you, operate our business, and provide information that you request form us. For example, data collected automatically on the Service may be used to help diagnose problems with our servers, to make our Service more useful, to customize it and personalize its content for you (for example, we will use your Health information to send you reminders to take your medications).\n\n" +
                        "● General communication – we also use your Personal Information to send you texts, emails or other communications regarding general adherence information, Service maintenance and other technical support, updates, or changes to this Privacy Policy or any other relevant agreements, and to respond to your inquiries.\n\n" +
                        "● Marketing purposes – subject to your marketing preferences, we may use your Personal Information (such as your email address or phone number) to communicate with you. We may also send you promotional material concerning our services or our partners’ services (which we believe may interest you), including but not limited to, by building an automated profile based on your Personal Information, for marketing purposes.\n" +
                        " ○ Opt-out of receiving marketing materials – If you do not want us to use or share your Personal Information for marketing purposes, you may opt-out by contacting us in accordance with this Privacy Policy, by clicking the “unsubscribe” button included in every marketing communication you receive from us, or with respect to tracking technologies, by using the cookie preferences menu displayed on our Site. Please note that even if you opt-out, we may still use and share your Personal Information with third parties for non-marketing purposes (for example to fulfill your requests, communicate with you and respond to your inquiries, etc.).\n\n" +
                        "● Analytics, surveys and research – we are always trying to improve our services and think of new and exciting features for our users. From time to time, we may conduct surveys or test features, and analyze the information we have to develop, evaluate and improve these features.\n\n" +
                        "● Protecting our interests – we may use your Personal Information when we believe it’s necessary in order to take precautions against liabilities, investigate and defend ourselves against any third party claims or allegations, investigate and protect ourselves from fraud, protect the security or integrity of our Service and protect the rights and property of MediCAL, its users and/or partners.\n\n" +
                        "● Enforcing of policies – we may use your Personal Information in order to enforce our policies, including but limited to this Privacy Policy, the Terms and Conditions and/or any applicable Program terms and policies.\n\n" +
                        "● Compliance with legal and regulatory requirements – we also use your Personal Information as required by law, regulation or other governmental authority, or to comply with a subpoena or similar legal process.\n\n" +
                        "WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION\n" +
                        "● Providers of personalized third party content – from time to time, we may also ask whether you would like us to share your Personal Information with another company that may want to send you information about their products or services. If you consent to such transfer by us of your Personal Information to another company, please note that the information provided will be subject to such company’s privacy practices and shall not be within our control.\n\n" +
                        "● Service providers – we may share your Personal Information, as is reasonably necessary, with our service providers, including vendors and suppliers that provide us with development services, technology (such as AWS), services, or content for the operation, development and maintenance of our Service or data and analysis on Service use, who are bound by an obligation of confidentiality, provided that we will only share Personal Information to.\n" +
                        "● Law authorities – we may share your personal data with law enforcement authorities, courts and tribunals, including with legal advisors and consultants, in case we need to respond to law enforcement requests or other legal requests or pursuant to a requirement imposed by law, order, judgment or decree, or courts in order to protect and defend our rights and property or those of Service users.\n" +
                "● Merger, acquisition or sale – we may transfer your Personal Information in the event of a merger, acquisition or sale of all or a portion of our assets.\n" +
                "Your Personal Information will not be combined with other information and will not be used for other purposes, except as explained in this Privacy policy. Please note that we are not subject to medical secrecy obligations.\n" +
                "● Personal Information you may share through our Service\n" +
                "  ○ Medfriend and Caregivers –\n" +
                "    ■ If you use the Services on your own behalf: You may send family members or friends an invitation to be your \"Medfriend\" or \"Caregiver\" by means of the Service, so that such person will receive alerts regarding your compliance with your medication regime. At your decision, your chosen Caregivers may also receive permissions to edit your information on the Services. By sending such invitation and granting such permissions, you represent that you have the right to appoint and provide the information of such person; that you consent to our disclosure of Personal Information about your medications and your compliance with your medication regime to such person; and, as applicable, that you allow your Caregiver to make changes to the Services including to your personal information, on your behalf. Sharing of your Personal Information and providing the editing permissions in this manner are solely at your responsibility.\n" +
                "    ■ If you use the Services on behalf of your child or an incapacitated person, you shall be considered such person's \"Medfriend\" or \"Caregiver\", as applicable. In such event, you represent and warrant that you have the legal authority to act on behalf of that person; that you will keep confidential and only use the Personal Information made available to you through the Services for the purpose for which it was made available to you; that any permission and personal information provided to you through the Services will be used with due care and only for that person's own good and best interests.\n" +
                "  ○ Medical professionals and Doctors – You may use the Service in order to share your Personal Information or other information with your doctor or healthcare providers. Such sharing may be enabled by inviting your healthcare provider to monitor your Personal Information, by accepting an invitation from your healthcare provider to download and use the Service, or otherwise using the Service settings to share your information with your healthcare provider; in these cases you consent to our sending Personal Information about your medications and your compliance with your medication regime with your healthcare providers. Confirm with your healthcare provider that they have sent you an invitation to use the Service. Such sharing of your information is at your discretion and is solely your responsibility.\n" +
                "While we take great care to keep your Personal Information confidential and secure, when you share your health or medication information with others or provide feedback regarding health matters, medications and otherwise, including by means of social media sites, or when you participate in a forum on the Service, any information disclosed by you in such way is solely your responsibility. You should exercise caution when disclosing any information (including Personal Information) in such ways, as you do not know who will access or use such information and for what purposes.\n" +
                "USE OF AGGREGATED DATA\n" +
                "We may de-identify and aggregate Personal Information; aggregated data will not contain any information that could be used to contact or identify you. We may analyze and/or combine all information we receive, including Health Information and information regarding your use of the Service, with information from other users to create aggregated data that may be disclosed to and utilized by us, our partners and by third parties without restriction, on commercial terms that we can determine in our sole discretion, for purposes such as content marketing, research purposes, in order to understand behavior patterns, in order to increase adherence to medication regimens, marketing strategies and for entering into commercial contracts in order to provide our users with the Service.\n" +
                "USER RIGHTS\n" +
                "Data protection laws in certain jurisdictions provide individuals with certain statutory rights with respect to their Personal Information.\n" +
                "We comply with applicable laws and respect the privacy rights of our users. If you wish to exercise any of your rights, or ask us a question, please contact us by using the contact details provided below.\n" +
                "However, please note that these rights are not absolute, and may be subject to our own legitimate interests and regulatory requirements.\n" +
                "RETENTION\n" +
                "We will retain your Personal Information for as long as necessary to provide the Services. We will retain and use your information as necessary to comply with our legal obligations, resolve disputes, and enforce our policies. Retention periods will be determined taking into account the type of information that is collected and the purpose for which it is collected, bearing in mind the requirements applicable to the situation.\n" +
                "LINKS TO OTHER WEBSITES OR APPS\n" +
                "Our Service may link to or refer to third-party websites or services that we do not own or control. Any Personal Information you provide is provided directly to such third party and is subject to such third party's provider's privacy policy. This Privacy Policy does not apply to such other websites or services, and we are not responsible for the privacy practices or content of any websites or services not controlled by us, nor are we responsible for such third party's use or misuse of your Personal Information. If you have any concerns, we urge you to review the terms of those other websites or services for more information about their applicable policies.\n" +
                "HOW WE PROTECT YOUR INFORMATION\n" +
                "We have implemented administrative, technical, and physical safeguards to help prevent unauthorized access, use, or disclosure of your Personal Information. Your information is stored on secure servers and isn't publicly available. We limit access to your information only to those employees or partners that need to know the information in order to enable the carrying out of the agreement between us.\n" +
                "While we seek to protect your information to ensure that it is kept confidential, no security system is infallible and impervious, and we cannot absolutely guarantee its security. You should be aware that there is always some risk involved in transmitting information over the internet. While we strive to protect your Personal Information, we cannot ensure or warrant the security and privacy of your Personal Information or other content you transmit using the Service, and you do so at your own risk.\n" +
                "You need to help us prevent unauthorized access to your account by protecting your password appropriately and limiting access to your account (for example, by signing off after you have finished accessing your account). You will be solely responsible for keeping your password confidential and for all use of your password and your account, including any unauthorized use.\n" +
                "CHILDREN\n" +
                "Our Service is intended for use by persons over the age of majority (as determined by applicable laws where such persons reside in: \"Age of Majority\"), unless we are provided with a valid parental or guardianship approval and consent, in accordance with the requirements of applicable laws. Under no circumstances should the Service be used by persons under the Age of Majority. We will not knowingly collect Personal Information from any person under the Age of Majority unless as described herein, and at our sole discretion. If you discover that a child has been using the Service without your consent, or that someone has been using the Service for or on behalf of your child without your consent, please contact us using the information below under \"How to Contact Us,\" and we will take reasonable steps to delete the child's information from our active databases. MediCAL reserves the right to check its user base from time to time and remove users whom MediCAL has grounds to believe they are in fact minors, including without limitation, restricting those user accounts, or deleting them, as MediCAL may deem appropriate.\n" +
                "HOW TO CONTACT US\n" +
                "If you have any questions, comments, requests, or concerns related to this Privacy Policy or the privacy practices of our Service, please contact us at:\n" +
                "MediCAL\n" +
                "info@MediCAL.com\n" +
                "ATTN: MediCAL\n";
        textViewPoliticas.setText(textoIngles);
        tituloPoliticas.setText("PRIVACY POLICY - MediCAL PROJECT");
    }
}

